/*
generated by comer,https://github.com/imoowi/comer
Copyright © 2023 jun<simpleyuan@gmail.com>
*/
package models

import (
	"github.com/imoowi/comer/components"
)

type RightBase struct{
	Name  string     `json:"name" form:"name" gorm:"column:name;type:varchar(30);not null;comment:名" `
}

// Right表
type Right struct {
	components.GormModel
	RightBase
}

// IModel.GetID实现
func (m *Right) GetID() uint {
	return m.ID
}
func (m *Right) SetId(id uint) {
	m.ID = id
}

// IModel.TableName实现
func (m *Right) TableName() string {
	return `right` + `s`
}
