/*
generated by comer,https://github.com/imoowi/comer
Copyright © 2023 jun<simpleyuan@gmail.com>
*/
package repos

import (
	"github.com/imoowi/live-stream-server/internal/global"
	"github.com/imoowi/live-stream-server/internal/models"
	"github.com/imoowi/comer/interfaces/impl"
)

var Menu *MenuRepo

type MenuRepo struct {
	impl.Repo[*models.Menu]
}

func NewMenuRepo() {
	db:=global.MysqlDb
	Menu = &MenuRepo{
		Repo: *impl.NewRepo[*models.Menu](db),
	}
}

func init() {
	RegisterRepos(NewMenuRepo)
}
