/*
generated by comer,https://github.com/imoowi/comer
Copyright © 2023 jun<simpleyuan@gmail.com>
*/
package repos

import (
	"github.com/imoowi/comer/interfaces/impl"
	"github.com/imoowi/live-stream-server/internal/global"
	"github.com/imoowi/live-stream-server/internal/models"
)

var RetweetStream *RetweetStreamRepo

type RetweetStreamRepo struct {
	impl.Repo[*models.RetweetStream]
}

func NewRetweetStreamRepo() {
	db := global.MysqlDb
	RetweetStream = &RetweetStreamRepo{
		Repo: *impl.NewRepo[*models.RetweetStream](db),
	}
}

func init() {
	RegisterRepos(NewRetweetStreamRepo)
}
