/*
generated by comer,https://github.com/imoowi/comer
Copyright © 2023 jun<simpleyuan@gmail.com>
*/
package repos

import (
	"github.com/imoowi/live-stream-server/internal/global"
	"github.com/imoowi/live-stream-server/internal/models"
	"github.com/imoowi/comer/interfaces/impl"
)

var Right *RightRepo

type RightRepo struct {
	impl.Repo[*models.Right]
}

func NewRightRepo() {
	db:=global.MysqlDb
	Right = &RightRepo{
		Repo: *impl.NewRepo[*models.Right](db),
	}
}

func init() {
	RegisterRepos(NewRightRepo)
}
