/*
generated by comer,https://github.com/imoowi/comer
Copyright © 2023 jun<simpleyuan@gmail.com>
*/
package repos

import (
	"github.com/imoowi/comer/interfaces/impl"
	"github.com/imoowi/live-stream-server/internal/global"
	"github.com/imoowi/live-stream-server/internal/models"
)

var Role *RoleRepo

type RoleRepo struct {
	impl.Repo[*models.Role]
}

func NewRoleRepo() {
	db := global.MysqlDb
	Role = &RoleRepo{
		Repo: *impl.NewRepo[*models.Role](db),
	}
}

func init() {
	RegisterRepos(NewRoleRepo)
}
