/*
generated by comer,https://github.com/imoowi/comer
Copyright © 2023 jun<simpleyuan@gmail.com>
*/
package repos

import (
	"github.com/gin-gonic/gin"
	"github.com/imoowi/comer/interfaces/impl"
	"github.com/imoowi/live-stream-server/internal/global"
	"github.com/imoowi/live-stream-server/internal/models"
)

var SrsHook *SrsHookRepo

type SrsHookRepo struct {
	impl.Repo[*models.SrsHook]
}

func NewSrsHookRepo() {
	db := global.MysqlDb
	SrsHook = &SrsHookRepo{
		Repo: *impl.NewRepo[*models.SrsHook](db),
	}
}

func init() {
	RegisterRepos(NewSrsHookRepo)
}

func (r *SrsHookRepo) Log(c *gin.Context, model *models.SrsHook) (ok bool, err error) {
	table := model.TableName() + `_` + model.Stream + `_XXX`
	db := r.DB.Client
	// r.DB.Client.Set("gorm:table_options", "ENGINE=InnoDB,COMMENT='srshook_log表'").Table(table).AutoMigrate(&model)
	global.MysqlDb.Client.Set("gorm:table_options", "ENGINE=InnoDB,COMMENT='hook表'").Table(table).AutoMigrate(&models.SrsHook{})
	err = db.Table(table).Save(&model).Error
	return
}
