/*
generated by comer,https://github.com/imoowi/comer
Copyright © 2023 jun<simpleyuan@gmail.com>
*/
package router

import (
	"github.com/gin-gonic/gin"
	"github.com/imoowi/live-stream-server/internal/controllers"
	"github.com/imoowi/live-stream-server/internal/middlewares"
)

func init() {
	RegisterRoute(AuthRouters)
}

func AuthRouters(e *gin.Engine) {
	api := e.Group(`/api`)
	{
		api.POST(`/auth-login`, middlewares.VcodeMiddleware(), controllers.AuthLogin)
		api.GET(`/auth-logout`, middlewares.JWTAuthMiddleware(), controllers.AuthLogout)
		api.POST(`/auth-chpwd`, middlewares.VcodeMiddleware(), middlewares.JWTAuthMiddleware(), controllers.AuthChgPwd)
	}

	//!import:do-not-delete-this-line,不要删除此行，主要用于代码生成器
}
