/*
generated by comer,https://github.com/imoowi/comer
Copyright © 2023 jun<simpleyuan@gmail.com>
*/
package router

import (
	"github.com/gin-gonic/gin"
	"github.com/imoowi/live-stream-server/internal/controllers"
)

func init() {
	RegisterRoute(EventRouters)
}

func EventRouters(e *gin.Engine) {
	api := e.Group("/api")
	// api.Use(middlewares.JWTAuthMiddleware())
	// api.Use(middlewares.CasbinMiddleware())
	// api.Use(middlewares.UserLogMiddleware())
	events := api.Group("/events")
	{
		events.GET("", controllers.EventPageList)   //分页
		events.GET("/:id", controllers.EventOne)    //一个
		events.POST("", controllers.EventAdd)       //新增
		events.PUT("/:id", controllers.EventUpdate) //更新
		events.DELETE("/:id", controllers.EventDel) //软删除
	}
	api.GET(`event-status`, controllers.EventStatus)
}
