/*
generated by comer,https://github.com/imoowi/comer
Copyright © 2023 jun<simpleyuan@gmail.com>
*/
package router

import (
	"github.com/gin-gonic/gin"
	"github.com/imoowi/live-stream-server/internal/controllers"
)

func init() {
	RegisterRoute(MenuRouters)
}

func MenuRouters(e *gin.Engine) {
	api := e.Group("/api")
	// api.Use(middlewares.JWTAuthMiddleware())
	// api.Use(middlewares.CasbinMiddleware())
	// api.Use(middlewares.UserLogMiddleware())
	menus := api.Group("/menus")
	{
		menus.GET("", controllers.MenuPageList)   //分页
		menus.GET("/:id", controllers.MenuOne)    //一个
		menus.POST("", controllers.MenuAdd)       //新增
		menus.PUT("/:id", controllers.MenuUpdate) //更新
		menus.DELETE("/:id", controllers.MenuDel) //软删除
	}
}
