/*
generated by comer,https://github.com/imoowi/comer
Copyright © 2023 jun<simpleyuan@gmail.com>
*/
package router

import (
	"github.com/gin-gonic/gin"
	"github.com/imoowi/live-stream-server/internal/middlewares"
	"github.com/imoowi/live-stream-server/internal/controllers"
)

func init() {
	RegisterRoute(Routers)
}

func Routers(e *gin.Engine) {
	api := e.Group("/api")
	api.Use(middlewares.JWTAuthMiddleware())
	api.Use(middlewares.CasbinMiddleware())
	api.Use(middlewares.UserLogMiddleware())
	retweetStreams := api.Group("/retweet-streams")
	{
		retweetStreams.GET("", controllers.RetweetStreamPageList) //分页
		retweetStreams.GET("/:id", controllers.RetweetStreamOne) //一个
		retweetStreams.POST("", controllers.RetweetStreamAdd) //新增
		retweetStreams.PUT("/:id", controllers.RetweetStreamUpdate) //更新
		retweetStreams.DELETE("/:id", controllers.RetweetStreamDel) //软删除
	}
}
