/*
generated by comer,https://github.com/imoowi/comer
Copyright © 2023 jun<simpleyuan@gmail.com>
*/
package router

import (
	"github.com/gin-gonic/gin"
	"github.com/imoowi/live-stream-server/internal/middlewares"
	"github.com/imoowi/live-stream-server/internal/controllers"
)

func init() {
	RegisterRoute(RightRouters)
}

func RightRouters(e *gin.Engine) {
	api := e.Group("/api")
	api.Use(middlewares.JWTAuthMiddleware())
	api.Use(middlewares.CasbinMiddleware())
	api.Use(middlewares.UserLogMiddleware())
	rights := api.Group("/rights")
	{
		rights.GET("", controllers.RightPageList) //分页
		rights.GET("/:id", controllers.RightOne) //一个
		rights.POST("", controllers.RightAdd) //新增
		rights.PUT("/:id", controllers.RightUpdate) //更新
		rights.DELETE("/:id", controllers.RightDel) //软删除
	}
}
