/*
generated by comer,https://github.com/imoowi/comer
Copyright © 2023 jun<simpleyuan@gmail.com>
*/
package router

import (
	"github.com/gin-gonic/gin"
	"github.com/imoowi/live-stream-server/internal/controllers"
	"github.com/imoowi/live-stream-server/internal/middlewares"
)

func init() {
	RegisterRoute(SrsHookRouters)
}

func SrsHookRouters(e *gin.Engine) {
	api := e.Group("/api")
	srsHooks := api.Group("/srs-hooks")
	{
		srsHooks.Use(middlewares.JWTAuthMiddleware())
		srsHooks.Use(middlewares.CasbinMiddleware())
		srsHooks.Use(middlewares.UserLogMiddleware())
		srsHooks.GET("", controllers.SrsHookPageList)   //分页
		srsHooks.GET("/:id", controllers.SrsHookOne)    //一个
		srsHooks.POST("", controllers.SrsHookAdd)       //新增
		srsHooks.PUT("/:id", controllers.SrsHookUpdate) //更新
		srsHooks.DELETE("/:id", controllers.SrsHookDel) //软删除
	}
	_srshooks := api.Group("/srshooks")
	{
		_srshooks.POST(`/streams/publish`, controllers.StreamPublish)      //推流，发起直播
		_srshooks.POST("/streams/unpublish", controllers.StreamsUnPublish) //结束直播
		_srshooks.POST("/sessions/play", controllers.SessionsPlay)         //开始观看
		_srshooks.POST("/sessions/stop", controllers.SessionsStop)         //停止观看
		_srshooks.POST("/dvrs", controllers.Dvrs)                          //录制
		_srshooks.POST("/hls", controllers.Hls)
		_srshooks.GET("/hls/*any", controllers.HlsMore)
	}
}
