/*
generated by comer,https://github.com/imoowi/comer
Copyright © 2023 jun<simpleyuan@gmail.com>
*/
package migrates

import (
	"github.com/imoowi/live-stream-server/internal/global"
	"github.com/imoowi/live-stream-server/internal/models"
)

func init() {
	RegisterMigrate(doSrsHookMigrate)
}
func doSrsHookMigrate() {
	global.MysqlDb.Client.Set("gorm:table_options", "ENGINE=InnoDB,COMMENT='hook表'").AutoMigrate(&models.SrsHook{})
}
