/*
generated by comer,https://github.com/imoowi/comer
Copyright © 2023 jun<simpleyuan@gmail.com>
*/
package services

import (
	"github.com/imoowi/comer/interfaces/impl"
	"github.com/imoowi/live-stream-server/internal/models"
	"github.com/imoowi/live-stream-server/internal/repos"
)

var Menu *MenuService

type MenuService struct {
	impl.Service[*models.Menu]
}

func NewMenuService(r *repos.MenuRepo) *MenuService {
	return &MenuService{
		Service: *impl.NewService[*models.Menu](r),
	}
}

func init() {
	RegisterServices(func() {
		Menu = NewMenuService(repos.Menu)
	})
}
