/*
generated by comer,https://github.com/imoowi/comer
Copyright © 2023 jun<simpleyuan@gmail.com>
*/
package services

import (
	"github.com/imoowi/comer/interfaces/impl"
	"github.com/imoowi/live-stream-server/internal/models"
	"github.com/imoowi/live-stream-server/internal/repos"
)

var RetweetStream *RetweetStreamService

type RetweetStreamService struct {
	impl.Service[*models.RetweetStream]
}

func NewRetweetStreamService(r *repos.RetweetStreamRepo) *RetweetStreamService {
	return &RetweetStreamService{
		Service: *impl.NewService[*models.RetweetStream](r),
	}
}

func init() {
	RegisterServices(func() {
		RetweetStream = NewRetweetStreamService(repos.RetweetStream)
	})
}
