/*
generated by comer,https://github.com/imoowi/comer
Copyright © 2023 jun<simpleyuan@gmail.com>
*/
package services

import (
	"github.com/imoowi/comer/interfaces/impl"
	"github.com/imoowi/live-stream-server/internal/models"
	"github.com/imoowi/live-stream-server/internal/repos"
)

var Right *RightService

type RightService struct {
	impl.Service[*models.Right]
}

func NewRightService(r *repos.RightRepo) *RightService {
	return &RightService{
		Service: *impl.NewService[*models.Right](r),
	}
}

func init() {
	RegisterServices(func() {
		Right = NewRightService(repos.Right)
	})
}
